export const chartConfigUI ={
caseStats:
    {
        theme: "fusion",
        showValues: "1",
        valueFontColor: "#ffffff",
        plotBorderAlpha: "0",
        legendBorderAlpha: "0",
        legendShadow: "0",
        showYAxisValues: "0",
        showToolTip: "1",
        legendPadding: "0px",
        labelPadding: "0",
        showXAxisLine: "0",
        divlineColor: "#999999",
        divLineIsDashed: "1",
        showLabels: "0",
        legendMargin: "0px",
        plotToolText: "$seriesname",
        showlegend: "1",
        legendMarkerType: "square",
        legendNumColumns: "0",
        showPercentValues: "0",
        patternSize: 1,
        patternDensity: 0.25,
        toolbarPosition: "BL",
        bgColor: "#ff0000",
        bgAlpha: "0",
        // xAxisLineColor: "#999999",
         legendItemFontSize: "12px",
        //chartLeftMargin: "30",
        // chartTopMargin: "10",
        // chartRightMargin: "25",
        //chartBottomMargin: "0",
        // Use Pattern Property
        // usePattern: "1",
        //patternType: "circle",
        //color: "#00ff99"
        // legendItemFontSize: "12px",
    },
    routerChart: { valueFontColor: "#ffffff",
    /*  baseFont: "Arial",
     labelFont: "Arial", */
     baseFontSize: "16",
     labelFontSize: "12",
     labelFontColor: "#FFFFFF",
     labelFontBold: "0",
     //paletteColors: "#92D050,#0D2747",
     bgColor: "#F2F2F2",
     bgAlpha: "0",
     divLineAlpha: "0",
     showCanvasBorder: "0",
     usePlotGradientColor: "0",
     plotBorderAlpha: "0",
     legendBorderAlpha: "0",
     legendShadow: "1",
     showYAxisValues: "0",
     showToolTip: "1",
     showPercentValues:"1",
     showLabels:"0",
     showValues:"1",
     plotToolText: "$label",
     theme:"fusion",
     showPlotBorder:"1",
     valuePosition:"Inside",
     minAngleForLabel:"360",
     interactiveLegend:"1",
     pieRadius:"70%",
     legendMarkerType: "square",
     legendItemFontSize: "12px",
     legendIconScale: ".8",
     "decimals": "0",},

    dailyStaffChart:{
        paletteColors:"#EF3226,#0D274D",
        showLabels:"1",
        showPlotBorder:"1",
        
        showHoverEffect:"1",
        isTrendZone:"1",
        valueFontSize:"10",
        formatNumber:"0",
        formatNumberScale:"0",
        bgColor:"#F2F2F2",
        bgAlpha:'0',
        legendPosition:"top",
        //xAxisNameBorderDashed:"1",
        theme: "fusion"
    },
    wecareDailyChart:{
        paletteColors:"#EF3226,#0D274D",
        showLabels:"1",
        showPlotBorder:"1",
        
        showHoverEffect:"1",
        isTrendZone:"1",
        valueFontSize:"10",
        formatNumber:"0",
        formatNumberScale:"0",
        bgColor:"#F2F2F2",
        bgAlpha:'0',
        legendPosition:"top",
        //xAxisNameBorderDashed:"1",
        theme: "fusion"
    },
    issueTypeChart:{
        
            paletteColors:"#F23228",
            showLabels:"1",
            showPlotBorder:"0",
           // valueFont:"Arial",
            showHoverEffect:"1",
            isTrendZone:"1",
            valueFontSize:"10",
            formatNumber:"0",
            formatNumberScale:"0",
            bgColor:"#F2F2F2",
            bgAlpha:"0",
           
            labelFontSize:"12",
            drawCrossLine:"1",
            divLineAlpha:"100",
            divLineColor:"#D9D9D9s",
            //usePattern:"1",
            //patternDensity:"1",
            "theme": "fusion"  
      
    }
}